"""user story model enhacment 

Revision ID: 0369b3a55f5c
Revises: 099ee47ddc7c
Create Date: 2026-02-02 01:05:08.131603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0369b3a55f5c'
down_revision: Union[str, None] = '099ee47ddc7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('theStory', sa.JSON(), nullable=True))
    op.drop_constraint('user_stories_room_id_fkey', 'user_stories', type_='foreignkey')
    op.drop_column('user_stories', 'extras')
    op.drop_column('user_stories', 'pipeline_stage')
    op.drop_column('user_stories', 'actor_custom')
    op.drop_column('user_stories', 'room_id')
    op.drop_column('user_stories', 'actor')
    op.drop_column('user_stories', 'work_item_type')
    op.drop_column('user_stories', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('work_item_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_stories', sa.Column('actor', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_stories', sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_stories', sa.Column('actor_custom', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('pipeline_stage', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_stories', sa.Column('extras', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key('user_stories_room_id_fkey', 'user_stories', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_stories', 'theStory')
    # ### end Alembic commands ###
