"""backlog modle

Revision ID: 099ee47ddc7c
Revises: 37a625b7d83c
Create Date: 2026-02-01 00:46:05.130251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099ee47ddc7c'
down_revision: Union[str, None] = '37a625b7d83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brds',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('business_objective', sa.String(), nullable=False),
    sa.Column('scopeIn', sa.String(), nullable=False),
    sa.Column('scopeOut', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brds_created_by'), 'brds', ['created_by'], unique=False)
    op.create_table('backlogs',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('brd_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brd_id'], ['brds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backlogs_created_by'), 'backlogs', ['created_by'], unique=False)
    op.add_column('goals', sa.Column('deadline', sa.DateTime(), nullable=False))
    op.add_column('key_results', sa.Column('target_value', sa.Float(), nullable=False))
    op.drop_column('key_results', 'current_value')
    op.add_column('user_stories', sa.Column('backlog_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'user_stories', 'backlogs', ['backlog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stories', type_='foreignkey')
    op.drop_column('user_stories', 'backlog_id')
    op.add_column('key_results', sa.Column('current_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('key_results', 'target_value')
    op.drop_column('goals', 'deadline')
    op.drop_index(op.f('ix_backlogs_created_by'), table_name='backlogs')
    op.drop_table('backlogs')
    op.drop_index(op.f('ix_brds_created_by'), table_name='brds')
    op.drop_table('brds')
    # ### end Alembic commands ###
