"""update todo model

Revision ID: 0b7a3f896ea4
Revises: a955f8edc281
Create Date: 2025-07-08 05:19:29.132581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7a3f896ea4'
down_revision: Union[str, None] = 'a955f8edc281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('todos', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('todos', 'is_chceked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_chceked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('todos', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('todos', 'is_deleted')
    # ### end Alembic commands ###
