"""remove room_id from sprint table

Revision ID: 18860d36a0d4
Revises: 0369b3a55f5c
Create Date: 2026-02-04 10:10:58.277013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18860d36a0d4'
down_revision: Union[str, None] = '0369b3a55f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sprints_room_id_fkey', 'sprints', type_='foreignkey')
    op.drop_column('sprints', 'room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('sprints_room_id_fkey', 'sprints', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
