"""change todo model

Revision ID: 1f0042cd6285
Revises: 18860d36a0d4
Create Date: 2026-02-23 21:12:01.885751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0042cd6285'
down_revision: Union[str, None] = '18860d36a0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('estimate', sa.Integer(), nullable=False))
    op.alter_column('todos', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('todos_sprint_id_fkey', 'todos', type_='foreignkey')
    op.drop_constraint('todos_room_id_fkey', 'todos', type_='foreignkey')
    op.drop_column('todos', 'is_deleted')
    op.drop_column('todos', 'room_id')
    op.drop_column('todos', 'sprint_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('sprint_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('todos', sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('todos', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('todos_room_id_fkey', 'todos', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key('todos_sprint_id_fkey', 'todos', 'sprints', ['sprint_id'], ['id'])
    op.alter_column('todos', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('todos', 'estimate')
    # ### end Alembic commands ###
