"""sprint model & enh relations 

Revision ID: 2bb3ae35a6e5
Revises: ae9138df19c2
Create Date: 2025-08-05 11:08:02.274802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb3ae35a6e5'
down_revision: Union[str, None] = 'ae9138df19c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_created_by'), 'sprints', ['created_by'], unique=False)
    op.create_table('user_stories',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sprint_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stories_created_by'), 'user_stories', ['created_by'], unique=False)
    op.add_column('rooms', sa.Column('product_owner_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'auth_user', ['product_owner_id'], ['id'])
    op.add_column('todos', sa.Column('sprint_id', sa.String(), nullable=True))
    op.add_column('todos', sa.Column('user_story_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'todos', 'sprints', ['sprint_id'], ['id'])
    op.create_foreign_key(None, 'todos', 'user_stories', ['user_story_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'user_story_id')
    op.drop_column('todos', 'sprint_id')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'product_owner_id')
    op.drop_index(op.f('ix_user_stories_created_by'), table_name='user_stories')
    op.drop_table('user_stories')
    op.drop_index(op.f('ix_sprints_created_by'), table_name='sprints')
    op.drop_table('sprints')
    # ### end Alembic commands ###
