"""deadline attribute in goal model

Revision ID: 37a625b7d83c
Revises: ef29c4f4fb85
Create Date: 2026-01-07 01:55:22.253437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a625b7d83c'
down_revision: Union[str, None] = 'ef29c4f4fb85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
