"""remove test_rollback column from user model

Revision ID: 4b3b1585e8d9
Revises: a1742edcc202
Create Date: 2026-04-26 15:25:40.416365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3b1585e8d9'
down_revision: Union[str, None] = 'a1742edcc202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'test_rollback')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('test_rollback', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
