"""update user story model 

Revision ID: 89e6ab5fd269
Revises: 2bb3ae35a6e5
Create Date: 2025-08-06 20:23:21.564070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e6ab5fd269'
down_revision: Union[str, None] = '2bb3ae35a6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('actor', sa.String(), nullable=False))
    op.add_column('user_stories', sa.Column('actor_custom', sa.String(), nullable=True))
    op.add_column('user_stories', sa.Column('acceptance_criteria', sa.Text(), nullable=True))
    op.add_column('user_stories', sa.Column('priority', sa.String(), nullable=False))
    op.add_column('user_stories', sa.Column('status', sa.String(), nullable=False))
    op.add_column('user_stories', sa.Column('story_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stories', 'story_points')
    op.drop_column('user_stories', 'status')
    op.drop_column('user_stories', 'priority')
    op.drop_column('user_stories', 'acceptance_criteria')
    op.drop_column('user_stories', 'actor_custom')
    op.drop_column('user_stories', 'actor')
    # ### end Alembic commands ###
