"""test_rollback

Revision ID: a1742edcc202
Revises: 1e8877954da3
Create Date: 2026-04-25 11:56:58.077719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1742edcc202'
down_revision: Union[str, None] = '1e8877954da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('test_rollback', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'test_rollback')
    # ### end Alembic commands ###
