"""room model

Revision ID: a4edade28e67
Revises: b137ee62da16
Create Date: 2025-07-30 14:08:08.619715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4edade28e67'
down_revision: Union[str, None] = 'b137ee62da16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desription', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('publishing_statu', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_created_by'), 'rooms', ['created_by'], unique=False)
    op.create_table('room_users',
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.add_column('todos', sa.Column('room_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'todos', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'room_id')
    op.drop_table('room_users')
    op.drop_index(op.f('ix_rooms_created_by'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
