"""update tasks model

Revision ID: a955f8edc281
Revises: 0c68957eb259
Create Date: 2025-07-08 01:03:10.329373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a955f8edc281'
down_revision: Union[str, None] = '0c68957eb259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('desription', sa.String(), nullable=False))
    op.add_column('todos', sa.Column('priority', sa.String(), nullable=False))
    op.add_column('todos', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('todos', 'status')
    op.drop_column('todos', 'priority')
    op.drop_column('todos', 'desription')
    # ### end Alembic commands ###
