"""announcement vote and comment models

Revision ID: b137ee62da16
Revises: 24e20c53ac6f
Create Date: 2025-07-17 07:45:48.895607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b137ee62da16'
down_revision: Union[str, None] = '24e20c53ac6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('subscription_plan', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_created_by'), 'organizations', ['created_by'], unique=False)
    op.create_table('announcements',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('target_departments', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('target_roles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('publish_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('publishing_status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', name='announcementstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_created_by'), 'announcements', ['created_by'], unique=False)
    op.create_table('announcement_comments',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('announcement_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_comments_created_by'), 'announcement_comments', ['created_by'], unique=False)
    op.create_table('announcement_votes',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('announcement_id', sa.String(), nullable=False),
    sa.Column('vote_type', sa.Enum('HELPFUL', 'UNHELPFUL', name='votetype'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'announcement_id', name='unique_user_vote')
    )
    op.create_index(op.f('ix_announcement_votes_created_by'), 'announcement_votes', ['created_by'], unique=False)
    op.add_column('auth_user', sa.Column('gender', sa.String(), nullable=False))
    op.add_column('auth_user', sa.Column('department', sa.String(), nullable=False))
    op.add_column('auth_user', sa.Column('role', sa.String(), nullable=False))
    op.add_column('auth_user', sa.Column('organization_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'auth_user', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_user', type_='foreignkey')
    op.drop_column('auth_user', 'organization_id')
    op.drop_column('auth_user', 'role')
    op.drop_column('auth_user', 'department')
    op.drop_column('auth_user', 'gender')
    op.drop_index(op.f('ix_announcement_votes_created_by'), table_name='announcement_votes')
    op.drop_table('announcement_votes')
    op.drop_index(op.f('ix_announcement_comments_created_by'), table_name='announcement_comments')
    op.drop_table('announcement_comments')
    op.drop_index(op.f('ix_announcements_created_by'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_organizations_created_by'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
