"""update enums

Revision ID: bbad8cb9a5d1
Revises: c0c3d59c7be9
Create Date: 2025-09-15 14:03:30.956778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbad8cb9a5d1'
down_revision: Union[str, None] = 'c0c3d59c7be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('rooms', 'publishing_statu')
    op.drop_column('rooms', 'desription')
    op.add_column('user_stories', sa.Column('work_item_type', sa.String(), nullable=False))
    op.add_column('user_stories', sa.Column('extras', sa.JSON(), nullable=True))
    op.alter_column('user_stories', 'order_rank',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=6),
               nullable=False)
    op.alter_column('user_stories', 'pipeline_stage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_stories', 'pipeline_stage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_stories', 'order_rank',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_stories', 'extras')
    op.drop_column('user_stories', 'work_item_type')
    op.add_column('rooms', sa.Column('desription', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('rooms', sa.Column('publishing_statu', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###
