"""RoomMembers model & enhacment on the previous models

Revision ID: c0c3d59c7be9
Revises: 89e6ab5fd269
Create Date: 2025-09-09 17:06:32.544299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c3d59c7be9'
down_revision: Union[str, None] = '89e6ab5fd269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_members',
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_in_room', sa.Enum('ADMIN', 'PO', 'MEMBER', 'VIEWER', name='roommemberrole'), nullable=False),
    sa.Column('capacity_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'LEFT', name='roommemberstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id', 'id')
    )
    op.create_index(op.f('ix_room_members_created_by'), 'room_members', ['created_by'], unique=False)
    op.create_index('ix_room_members_status', 'room_members', ['room_id', 'status'], unique=False)
    op.drop_table('room_users')
    op.add_column('rooms', sa.Column('sprint_length_days', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('visibility', sa.String(), nullable=False))
    op.add_column('rooms', sa.Column('methodology', sa.String(), nullable=False))
    op.drop_constraint('sprints_room_id_fkey', 'sprints', type_='foreignkey')
    op.create_foreign_key(None, 'sprints', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_stories', sa.Column('order_rank', sa.Integer(), nullable=True))
    op.add_column('user_stories', sa.Column('pipeline_stage', sa.String(), nullable=True))
    op.add_column('user_stories', sa.Column('room_id', sa.String(), nullable=False))
    op.alter_column('user_stories', 'sprint_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'user_stories', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stories', type_='foreignkey')
    op.alter_column('user_stories', 'sprint_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user_stories', 'room_id')
    op.drop_column('user_stories', 'pipeline_stage')
    op.drop_column('user_stories', 'order_rank')
    op.drop_constraint(None, 'sprints', type_='foreignkey')
    op.create_foreign_key('sprints_room_id_fkey', 'sprints', 'rooms', ['room_id'], ['id'])
    op.drop_column('rooms', 'methodology')
    op.drop_column('rooms', 'visibility')
    op.drop_column('rooms', 'sprint_length_days')
    op.create_table('room_users',
    sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='room_users_room_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='room_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('room_id', 'user_id', name='room_users_pkey')
    )
    op.drop_index('ix_room_members_status', table_name='room_members')
    op.drop_index(op.f('ix_room_members_created_by'), table_name='room_members')
    op.drop_table('room_members')
    # ### end Alembic commands ###
