"""goal model

Revision ID: ef29c4f4fb85
Revises: bbad8cb9a5d1
Create Date: 2026-01-05 21:50:29.162183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef29c4f4fb85'
down_revision: Union[str, None] = 'bbad8cb9a5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_created_by'), 'goals', ['created_by'], unique=False)
    op.create_table('key_results',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_results_created_by'), 'key_results', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_results_created_by'), table_name='key_results')
    op.drop_table('key_results')
    op.drop_index(op.f('ix_goals_created_by'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
