server {
    listen 80;
    server_name ruyahub.club;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'SSL initializing...';
        add_header Content-Type text/plain;
    }
}
